#==========================================
# 환경 구분이 필요 없는 공통 Property 설정을 관리.
# local, dev, stg, prd 환경으로 구분.
#==========================================
spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#==========================================
# End-Point BaseURL
# DB에서 관리하고 있으나 로컬DB 백업용 입니다.
#==========================================
endpoints:
  kakao:
    base-url: https://dapi.kakao.com
  naver:
    base-url: https://openapi.naver.com

#==========================================
# application system configurations
#==========================================
system:
  #===============================================
  # 시스템 속성 정의 : SKYNET
  #===============================================
  application-name: place-search
  keyword-cache:
    live-seconds: 5
