#===========================================
# 환경 : [local PC]
#===========================================
server:
  port: 8087

#===========================================
# logging
# detailed design : resources/logger/logback-{active}.xml
#===========================================
logging:
  config: classpath:logger/logback-local.xml
  file:
    path: ./logs

#===========================================
# spring
#===========================================
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    continue-on-error: true
    hikari:
      driver-class-name: org.h2.Driver
      #jdbc-url: jdbc:h2:./database/placeH2DB
      jdbc-url: jdbc:h2:tcp://localhost:9095/./database/placeH2DB;MODE=MySQL
      password: pilsa115
      username: pilsa115

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    #default-property-inclusion: non_default

